# Generated by Django 5.1.3 on 2024-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
